language: csharp
solution: DHT.sln

script:
  - xbuild /p:Configuration=Debug DHT.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore DHT.sln
after_script:
  - nunit-console ./DHT.Tests/bin/Release/DHT.Tests.dll